integrate SML/NJ benchmark script

diff --git a/benchmark/benchmarks/makefile.smlnj b/benchmark/benchmarks/makefile.smlnj
--- a/benchmark/benchmarks/makefile.smlnj
+++ b/benchmark/benchmarks/makefile.smlnj
@@ -1,20 +1,18 @@
 #!/bin/sh
 
-ARCH=x86-linux
-OS=linux
-(* sml/nj *)
+# sml/nj
 SML=sml
 
 # build
 function build_nj () {
 	local readonly bench=$1
-	ml-build $bench/sources.cm Test.main $bench/sources.${ARCH}-${OS}
+	ml-build $bench/sources.cm Test.main $bench/doit
 }
 
 function run_nj () {
 	local readonly bench=$1
 	cd $bench
-		${SML} @SMLload=sources.${ARCH}-${OS}
+		${SML} @SMLload=doit
 	cd ..
 }
 
@@ -31,27 +29,23 @@ BENCHMARKS='boyer count_graphs cpstak diviter divrec fft gcbench knuth_bendix le
 			nucleic perm9 puzzle ratio_regions ray tsp'
 for bench in $BENCHMARKS
 do
+	echo "build [$bench]..." >&2
 	build_nj $bench
-	if [ $? -eq 0 ]; then
-		echo "build success [$bench]" >&2
-	else
-		echo "build failure [$bench]" >&2
-	fi
 done
 
 
-# run
-${SML} < coresml/fibonacci.sml
-
-for bench in $BENCHMARKS
-do
-	run_nj $bench >/dev/null
-	if [ $? -eq 0 ]; then
-		echo "run success [$bench]" >&2
-	else
-		echo "run failure [$bench]" >&2
-	fi
-done
-
-
-
+## run
+#${SML} < coresml/fibonacci.sml
+#
+#for bench in $BENCHMARKS
+#do
+#	run_nj $bench >/dev/null
+#	if [ $? -eq 0 ]; then
+#		echo "run success [$bench]" >&2
+#	else
+#		echo "run failure [$bench]" >&2
+#	fi
+#done
+#
+#
+#
